#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | traefik:help)
    help_content_func () {
      declare desc="return help_content string"
      cat<<help_content
    Traefik proxy for Dokku installed.
help_content
    }
    help_content_func
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
