#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"
source "$PLUGIN_AVAILABLE_PATH/traefik-proxy/functions"

traefik_get_deploy_args() {
  declare desc="sets the labels on deployment"
  local APP="$1" IMAGE_TAG="$2" PROC_TYPE="$3" CONTAINER_INDEX="$4"
  local output=""
  traefik_build_labels
  if [[ "$PROC_TYPE" == "web" ]] && \
     [[ "$(traefik_is_enabled "$APP")" == "True" ]] && \
     [[ "$(get_app_proxy_type "$APP")" == "traefik" ]]; then
    output=" --label-file $(traefik_get_label_file ${APP})"
  fi
  echo -n "$STDIN$output"
}

traefik_get_deploy_args "$@"
