#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/traefik-proxy/functions"
docker pull traefik
NET_EXISTS="$(docker network ls | tail -n +2 | awk -F ' ' '{print $2}' | grep $(traefik_get_network_for_proxy))"
if [[ ! -n ${NET_EXISTS} ]]; then
    docker network create $(traefik_get_network_for_proxy)
fi
sed -i "s;{{DOMAIN}};$(cat $DOKKU_ROOT/VHOST);g" ${PLUGIN_AVAILABLE_PATH}/traefik-proxy/traefik.toml
sed -i "s;{{DOMAIN}};$(cat $DOKKU_ROOT/VHOST);g" ${PLUGIN_AVAILABLE_PATH}/traefik-proxy/traefik.flags
sed -i "s;{{PROXY_NET}};$(traefik_get_network_for_proxy);g" ${PLUGIN_AVAILABLE_PATH}/traefik-proxy/traefik.flags
mkdir -p ${PLUGIN_AVAILABLE_PATH}/traefik-proxy/acme
touch ${PLUGIN_AVAILABLE_PATH}/traefik-proxy/acme/acme.json
docker run -d -p 80:80 -p 443:443 \
    -v ${PLUGIN_AVAILABLE_PATH}/traefik-proxy/traefik.toml:/etc/traefik/traefik.toml \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v ${PLUGIN_AVAILABLE_PATH}/traefik-proxy/acme:/etc/traefik/acme \
    --label-file="${PLUGIN_AVAILABLE_PATH}/traefik-proxy/traefik.flags" \
    --name="traefik-dokku-proxy" \
    --network="$(traefik_get_network_for_proxy)" traefik > ${PLUGIN_AVAILABLE_PATH}/traefik-proxy/CONTAINER
