#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/docker-options/functions"
source "$PLUGIN_AVAILABLE_PATH/traefik-proxy/functions"

traefik_post_create() {
  declare desc="traefik-proxy post-create plugin trigger"
  local trigger="traefik-proxy_post_create"
  local APP="$1"

  local passed_phases=(run deploy)
  add_passed_docker_option passed_phases[@] "--network=$(traefik_get_network_for_proxy)"

}

traefik_post_create "$@"
