#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"

traefik_post_domains_update() {
  declare desc="catch domain name events for Traefik"
  declare trigger="traefik_post_domains_update"
  declare APP="$1"
  local ACTION_NAME="$2"
  local DOMAINS=""
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"

  for i in "${@:2}"; do
     DOMAINS+="--domain ${i} "
  done

  if [[ "$(get_app_proxy_type "$APP")" = "traefik" ]]; then
    plugn trigger network-build-config "$APP"
    /usr/bin/env python3 traefik.py --set-domains --app_name "$APP" --dokku_root "$DOKKU_ROOT" ${DOMAINS} \
    --action "$ACTION_NAME"
  fi
}

traefik_post_domains_update "$@"
