#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"
source "$PLUGIN_AVAILABLE_PATH/traefik-proxy/functions"

traefik_post_domains_update() {
  declare desc="catch domain name events for Traefik"
  declare trigger="traefik_post_domains_update"
  declare APP="$1"
  shift
  local ACTION_NAME="$1"
  shift
  local DOMAINS=""
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"

  while [[ "$1" != "" ]]; do
     DOMAINS+="--domain ${1} "
     shift
  done

  if [[ "$(get_app_proxy_type "$APP")" == "traefik" ]]; then
    plugn trigger network-build-config "$APP"
    traefik_call_script --update_domains --app_name "$APP" \
    --dokku_root "$DOKKU_ROOT" ${DOMAINS} \
    --update_domains_action "$ACTION_NAME"
    traefik_build_labels
  fi
}

traefik_post_domains_update "$@"
