#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/proxy/functions"
source "$PLUGIN_AVAILABLE_PATH/traefik-proxy/functions"

traefik_proxy_disable() {
  declare desc="build traefik config to proxy app containers from command line"
  declare trigger="traefik_proxy_build_config"
  declare APP="$1"
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"

  if [[ "$(get_app_proxy_type "$APP")" == "traefik" ]]; then
    traefik_call_script --disable_proxy --app_name "$APP" --dokku_root "$DOKKU_ROOT"
  fi
}

traefik_proxy_disable "$@"
