#!/usr/bin/env bash
# Cleanup up extra containers created
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/traefik-proxy/functions"

cat ${PLUGIN_AVAILABLE_PATH}/traefik-proxy/CONTAINER | docker stop | docker rm
