#!/usr/bin/env bash
# Cleanup up extra containers created
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/traefik-proxy/functions"

docker rm $(docker stop $(cat ${PLUGIN_AVAILABLE_PATH}/traefik-proxy/CONTAINER))
